import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'

import type { components } from '../generated/openapi-types'
import { defineCommand } from '../lib/define-command'
import { rawRequest } from '../lib/raw-request'

type TriggerRow = components['schemas']['TriggerRow']

/**
 * `brew-cli types` — generate TypeScript payload contracts for this
 * workspace's triggers (declared `payloadSchema`). Deterministic output:
 * same inputs → the same bytes, with a content hash in the header so
 * `--check` works as a CI drift gate (exit 1 when the API's contracts no
 * longer match the committed file).
 */

const HEADER_PREFIX = '// brew:contracts sha256:'

/**
 * THE canonical type-name rule, mirrored byte-for-byte from the app's
 * `lib/payload-contract/codegen.ts` (`contractTypeName`) so Copy-as, the
 * SKILL.md brief, and this file all mint the SAME identifier for one
 * contract: PascalCase(name || id) + `Payload`, digit-led names prefixed,
 * an existing `…Payload` suffix never doubled, symbol-only names →
 * `ContractPayload`.
 */
function pascalCase(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9]+/g, ' ').trim()
  if (cleaned === '') {
    return 'Contract'
  }
  return cleaned
    .split(' ')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

function typeName(label: string): string {
  const base = pascalCase(label)
  if (/^[0-9]/.test(base)) {
    return `Payload${base}`
  }
  return base.endsWith('Payload') ? base : `${base}Payload`
}

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function propertyKey(key: string): string {
  return IDENTIFIER_RE.test(key) ? key : JSON.stringify(key)
}

function triggerFieldType(type: string): string {
  if (type === 'int') {
    return 'number'
  }
  if (type === 'boolean') {
    return 'boolean'
  }
  return 'string'
}

function emitTriggerType(trigger: TriggerRow, name: string): string {
  const fields = trigger.payloadSchema?.fields ?? []
  const lines = fields.map((field) => {
    const optional = field.required ? '' : '?'
    return `  ${propertyKey(field.key)}${optional}: ${triggerFieldType(field.type)}`
  })
  const body =
    fields.length === 0
      ? `export type ${name} = Record<string, never>`
      : [`export type ${name} = {`, ...lines, '}'].join('\n')
  return [
    `/** Fire: POST /v1/automations/triggers/${trigger.triggerEventId}/fire — body { payload: ${name} } */`,
    body,
  ].join('\n')
}

/** Byte-stable ordering — `localeCompare` varies by host locale. */
function byCodepoint(a: string, b: string): number {
  if (a < b) {
    return -1
  }
  return a > b ? 1 : 0
}

/**
 * Trigger titles share one flat namespace and carry no uniqueness
 * constraint — colliding names get the trigger id appended (then a
 * numeric suffix as a last resort) so the generated file always compiles.
 */
function uniqueNames(
  entries: ReadonlyArray<{ label: string; id: string }>
): Array<string> {
  const taken = new Map<string, number>()
  return entries.map(({ label, id }) => {
    let name = typeName(label)
    if (taken.has(name)) {
      const suffixed = `${name}${pascalCase(id)}`
      name = suffixed
    }
    while (taken.has(name)) {
      const bump = (taken.get(name) ?? 1) + 1
      taken.set(name, bump)
      name = `${name}${bump}`
    }
    taken.set(name, 1)
    return name
  })
}

function buildFileText(args: { triggers: ReadonlyArray<TriggerRow> }): string {
  const triggers = [...args.triggers].sort((a, b) =>
    byCodepoint(a.triggerEventId, b.triggerEventId)
  )
  // ONE name pass: same rule as the app (name || id), collisions
  // resolved deterministically.
  const names = uniqueNames(
    triggers.map((t) => ({ id: t.triggerEventId, label: t.title }))
  )
  const triggerBlocks = triggers.map((t, i) =>
    emitTriggerType(t, names[i] ?? typeName(t.title))
  )
  const body = [
    '// Generated by `brew-cli types` — do not edit by hand.',
    '// Re-run `brew-cli types` after changing a trigger schema; gate',
    '// drift in CI with `brew-cli types --check`.',
    '',
    triggerBlocks.join('\n\n'),
    '',
  ].join('\n')
  const hash = createHash('sha256').update(body).digest('hex')
  return `${HEADER_PREFIX}${hash}\n${body}`
}

export const typesCommand = defineCommand({
  path: ['types'],
  summary:
    "Generate TypeScript payload contracts for this workspace's triggers into your codebase; --check is the CI drift gate (exit 1 on drift). Needs the automations scope",
  sdkMethod: null,
  isRawTransport: true,
  route: { method: 'GET', path: '/v1/automations/triggers' },
  commandClass: 'read',
  flags: [
    {
      flag: '--out <file>',
      summary: 'Output file (default brew-contracts.ts)',
      defaultValue: 'brew-contracts.ts',
    },
    {
      flag: '--check',
      summary:
        'Verify the output file is up to date instead of writing; exits 1 on drift',
    },
  ],
  examples: [
    'brew-cli types',
    'brew-cli types --out src/brew-contracts.ts',
    'brew-cli types --check',
  ],
  run: async ({ ctx, flags }) => {
    // Follow the cursor to the end — a silent 100-trigger cap would make
    // `--check` certify an incomplete file (integration catalogs alone
    // can cross 100). The page ceiling is a runaway-loop backstop only.
    const triggers: Array<TriggerRow> = []
    let cursor: string | null = null
    for (let page = 0; page < 50; page++) {
      const url: string = cursor
        ? `/v1/automations/triggers?limit=100&cursor=${encodeURIComponent(cursor)}`
        : '/v1/automations/triggers?limit=100'
      const listResponse: {
        data: Array<TriggerRow>
        pagination?: { cursor: string | null; hasMore: boolean }
      } = await rawRequest(ctx, { method: 'GET', path: url })
      triggers.push(...(listResponse.data ?? []))
      if (
        !listResponse.pagination?.hasMore ||
        !listResponse.pagination.cursor
      ) {
        break
      }
      cursor = listResponse.pagination.cursor
    }
    const text = buildFileText({ triggers })
    const outPath =
      typeof flags.out === 'string' ? flags.out : 'brew-contracts.ts'

    if (flags.check === true) {
      let existing: string | null = null
      try {
        existing = readFileSync(outPath, 'utf8')
      } catch {
        existing = null
      }
      // CRLF-tolerant: an autocrlf checkout must not read as drift.
      const normalize = (value: string) => value.replaceAll('\r\n', '\n')
      if (existing === null || normalize(existing) !== normalize(text)) {
        return {
          data: { checked: outPath, upToDate: false },
          human:
            existing === null
              ? `${outPath} does not exist — run \`brew-cli types\` first.`
              : `${outPath} is stale — the workspace's payload contracts changed. Run \`brew-cli types\` to regenerate.`,
          // Documented drift contract: exit 1 (not the usage-error 2).
          exitCode: 1,
        }
      }
      return {
        data: { checked: outPath, upToDate: true },
        human: `${outPath} is up to date.`,
      }
    }

    writeFileSync(outPath, text)
    return {
      data: {
        out: outPath,
        triggers: triggers.length,
      },
      human: `Wrote ${outPath} (${triggers.length} trigger${triggers.length === 1 ? '' : 's'}).`,
    }
  },
})
